In [9]:
my_list = [1,2,3]

In [10]:
import numpy as np

In [11]:
arr = np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [15]:
my_mat = [[1,2,3],[4,5,6,7]]

In [16]:
np.array(my_mat)

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [38]:
np.arange(0,12,2) #Generates number from 0 to 11 incrementing by 2

array([ 0,  2,  4,  6,  8, 10])

In [37]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [29]:
#Equally spaced number between a range
np.linspace(0,1,9)

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [30]:
np.eye(3)  #Identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [31]:
np.random.rand(5) #Generates random nbrs between 0 and 1 from uniform distribution

array([ 0.75680498,  0.3788319 ,  0.85129881,  0.53544177,  0.62107613])

In [33]:
np.random.rand(2,3) #Generates random Matrix between 0 and 1 from uniform distribution

array([[ 0.68812521,  0.77827013,  0.41526803],
       [ 0.5344056 ,  0.71184207,  0.45382952]])

In [34]:
np.random.randn(2,3) #Generates random Matrix between 0 and 1 from nornal distribution with mean 0 and sd=1

array([[ 1.08108043,  0.96581959, -1.43375007],
       [ 0.30086437,  0.23877144, -0.85691162]])

In [36]:
np.random.randint(1,100,20) #Sample 20 numbers between 1 and 99

array([ 7, 51, 71, 63,  3, 82, 92, 70, 85, 88, 94, 82, 68, 31, 66, 73, 77,
       93, 60, 15])

In [39]:
arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
mt=arr.reshape(3,3) #Convert a vector to matrix
mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr.max() #Find maximum value
arr.argmin() #Returns index of minimum value

0

In [47]:
mt.shape #Returns matrix dimensions

(3L, 3L)

In [48]:
from numpy.random import randint
randint(2,10)

2