In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1,200,15).reshape(3,5)
arr

array([[122,  52, 153, 152, 192],
       [194, 105, 144,  44, 151],
       [154, 114,  93, 190, 182]])

In [8]:
arr[1,1] #get element in 2nd row and 2nd col

105

In [10]:
arr[:,3] #all elements of 4th col

array([152,  44, 190])

In [14]:
arr[1:3,3] #gets element from 4th col and 1,2 rows

array([ 44, 190])

In [16]:
slice_array = arr[:,:]
slice_array

array([[122,  52, 153, 152, 192],
       [194, 105, 144,  44, 151],
       [154, 114,  93, 190, 182]])

In [18]:
slice_array[:,1] = 0
slice_array
arr #Changes even the original array as slice has only referenced arr 

array([[122,   0, 153, 152, 192],
       [194,   0, 144,  44, 151],
       [154,   0,  93, 190, 182]])

In [22]:
arrc = arr.copy()
arrc
arrc[:,2] = 0
arrc
arr  # The original array is not impacted because we created a copy of the array

array([[122,   0, 153, 152, 192],
       [194,   0, 144,  44, 151],
       [154,   0,  93, 190, 182]])

In [23]:
arr[0][1] #Double bracket notation

0

In [29]:
#Conditional selection
vec = np.arange(0,11)
vec
vec[vec > 5]   # vec > 5 gives a Booleann array

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr>0,].size

12

In [36]:
arr + arr # Add elements of array

array([[244,   0, 306, 304, 384],
       [388,   0, 288,  88, 302],
       [308,   0, 186, 380, 364]])

In [37]:
arr + 10 # Add 10 to each element

array([[132,  10, 163, 162, 202],
       [204,  10, 154,  54, 161],
       [164,  10, 103, 200, 192]])

In [41]:
arr/arr #Warning for 0/0, result is 0

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([[1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1]])

In [44]:
np.sqrt(arr)#Square root of all elements
np.exp(arr) #Exponent
np.log(arr) #Log

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 4.80402104,        -inf,  5.03043792,  5.02388052,  5.25749537],
       [ 5.26785816,        -inf,  4.9698133 ,  3.78418963,  5.01727984],
       [ 5.0369526 ,        -inf,  4.53259949,  5.24702407,  5.20400669]])

In [49]:
np.linalg.inv(arr[:,2:5]) #Matrix Inverse

array([[ 0.0378812 , -0.01614741, -0.02656556],
       [ 0.02228144, -0.01829771, -0.00832463],
       [-0.04261773,  0.02735315,  0.02775977]])